[project]
name = "llm_style"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.5.2",
    "datasets>=3.5.0",
<<<<<<< HEAD
    "evaluate>=0.4.3",
=======
>>>>>>> 07a2dcb1db0582cb05df8967782501f91b5f882a
    "lightning-transformers>=0.2.5",
    "matplotlib>=3.10.1",
    "openai>=1.70.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.50.3",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]
package = true
